// Mock data for Haozing platform

export const PROPERTIES = [
  {
    id: '1',
    title: 'Luxury Ocean View Suite',
    location: 'Nyali, Mombasa',
    price: 8500,
    rating: 4.9,
    reviewCount: 127,
    type: 'Apartment',
    beds: 2,
    baths: 2,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    amenities: ['WiFi', 'Pool', 'Parking', 'Kitchen', 'AC', 'Ocean View'],
    verified: true,
    instantBook: true,
    hostId: 'h1',
    hostName: 'Amina Wanjiru',
    hostAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=100',
    description: 'Breathtaking ocean views from every room. This modern suite features an infinity pool, fully equipped kitchen, and direct beach access.',
    wifiSpeed: '50 Mbps',
    electricity: 'Stable (backup generator)',
    water: 'Reliable (24/7)',
    safetyScore: 9.2,
    tag: 'trending',
    lat: -4.0435,
    lng: 39.6682,
  },
  {
    id: '2',
    title: 'Watamu Beachfront Villa',
    location: 'Watamu, Kilifi County',
    price: 15000,
    rating: 4.8,
    reviewCount: 89,
    type: 'Villa',
    beds: 3,
    baths: 2,
    guests: 6,
    images: [
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Private Pool', 'Beach Access', 'AC', 'Ocean View'],
    verified: true,
    instantBook: false,
    hostId: 'h2',
    hostName: 'David Kipchoge',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    description: 'Stunning beachfront villa overlooking the turquoise waters of Watamu Marine Park. Private pool, direct beach access, and modern Swahili architecture.',
    wifiSpeed: '20 Mbps',
    electricity: 'Stable (backup generator)',
    water: 'Reliable',
    safetyScore: 8.8,
    tag: 'luxury',
    lat: -3.35,
    lng: 39.98,
  },
  {
    id: '3',
    title: 'Mtwapa Beach Studio',
    location: 'Mtwapa, Mombasa',
    price: 4200,
    rating: 4.7,
    reviewCount: 203,
    type: 'Studio',
    beds: 1,
    baths: 1,
    guests: 2,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['WiFi', 'Parking', 'Beach Access', 'Security', 'Kitchen'],
    verified: true,
    instantBook: true,
    hostId: 'h3',
    hostName: 'Grace Mwacharo',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    description: 'Cozy studio near Mtwapa Creek with easy beach access. Perfect for budget travelers exploring the north coast.',
    wifiSpeed: '50 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.5,
    tag: 'budget',
    lat: -3.95,
    lng: 39.75,
  },
  {
    id: '4',
    title: 'Diani Beach Cottage',
    location: 'Diani, Kwale',
    price: 7200,
    rating: 4.95,
    reviewCount: 64,
    type: 'Cottage',
    beds: 2,
    baths: 1,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    ],
    amenities: ['WiFi', 'Beach Access', 'BBQ', 'Kitchen', 'Garden'],
    verified: true,
    instantBook: true,
    hostId: 'h4',
    hostName: 'Sarah Omondi',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    description: 'Charming beachfront cottage with direct access to Diani\'s white sandy beaches. Perfect for couples and families.',
    wifiSpeed: '25 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 9.0,
    tag: 'trending',
    lat: -4.3219,
    lng: 39.5678,
  },
  {
    id: '5',
    title: 'Shanzu Beach House',
    location: 'Shanzu, Mombasa',
    price: 11500,
    rating: 4.85,
    reviewCount: 47,
    type: 'House',
    beds: 4,
    baths: 3,
    guests: 8,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    ],
    amenities: ['WiFi', 'Pool', 'Garden', 'Parking', 'Kitchen', 'Beach Access'],
    verified: true,
    instantBook: false,
    hostId: 'h5',
    hostName: 'James Mwaringa',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    description: 'Spacious beach house in Shanzu with private pool and direct beach access. Perfect for family gatherings and groups.',
    wifiSpeed: '60 Mbps',
    electricity: 'Stable (inverter backup)',
    water: 'Reliable',
    safetyScore: 9.2,
    tag: 'luxury',
    lat: -3.97,
    lng: 39.75,
  },
  {
    id: '6',
    title: 'Bamburi Beach Apartment',
    location: 'Bamburi, Mombasa',
    price: 3500,
    rating: 4.6,
    reviewCount: 156,
    type: 'Apartment',
    beds: 1,
    baths: 1,
    guests: 2,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
    ],
    amenities: ['WiFi', 'Pool', 'Beach Access', 'Security', 'Kitchen'],
    verified: true,
    instantBook: true,
    hostId: 'h6',
    hostName: 'Aisha Ali',
    hostAvatar: 'https://images.unsplash.com/photo-1546961342-ea5f62d5a27b?w=100',
    description: 'Modern apartment in Bamburi with pool access and short walk to the beach. Great value for coastal getaways.',
    wifiSpeed: '45 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.9,
    tag: 'budget',
    lat: -3.98,
    lng: 39.72,
  },
  {
    id: '7',
    title: 'Lamu Stone Town Retreat',
    location: 'Lamu Island, Coast',
    price: 9800,
    rating: 4.95,
    reviewCount: 72,
    type: 'Villa',
    beds: 3,
    baths: 2,
    guests: 6,
    images: [
      'https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=800',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    ],
    amenities: ['WiFi', 'Rooftop Terrace', 'Kitchen', 'AC', 'Ocean View', 'Breakfast'],
    verified: true,
    instantBook: false,
    hostId: 'h7',
    hostName: 'Fatuma Ali',
    hostAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100',
    description: 'A beautifully restored Swahili stone house in the heart of Lamu Old Town. Rooftop terrace with panoramic sea views, carved wooden doors, and a peaceful courtyard.',
    wifiSpeed: '15 Mbps',
    electricity: 'Stable (solar backup)',
    water: 'Reliable',
    safetyScore: 9.1,
    tag: 'luxury',
    lat: -2.2694,
    lng: 40.9022,
  },
  {
    id: '8',
    title: 'Kilifi Creek Cottage',
    location: 'Kilifi, Kilifi County',
    price: 6500,
    rating: 4.8,
    reviewCount: 38,
    type: 'Cottage',
    beds: 2,
    baths: 1,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Garden', 'Parking', 'Creek View', 'Boat Dock'],
    verified: true,
    instantBook: true,
    hostId: 'h8',
    hostName: 'Samuel Charo',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    description: 'Charming cottage on the banks of Kilifi Creek. Watch dhows sail by and enjoy the peaceful coastal atmosphere.',
    wifiSpeed: '35 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.8,
    tag: 'trending',
    lat: -3.63,
    lng: 39.85,
  },
  {
    id: '9',
    title: 'Vipingo Ridge Studio',
    location: 'Vipingo, Kilifi County',
    price: 3200,
    rating: 4.6,
    reviewCount: 91,
    type: 'Studio',
    beds: 1,
    baths: 1,
    guests: 2,
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['WiFi', 'AC', 'Kitchen', 'Security', 'Golf View'],
    verified: true,
    instantBook: true,
    hostId: 'h9',
    hostName: 'Achieng Mwangi',
    hostAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100',
    description: 'Modern studio overlooking the Vipingo Ridge golf course. Quiet location perfect for remote work and relaxation.',
    wifiSpeed: '55 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 9.0,
    tag: 'budget',
    lat: -3.8,
    lng: 39.75,
  },
  {
    id: '10',
    title: 'Msambweni Beach Villa',
    location: 'Msambweni, Kwale',
    price: 12000,
    rating: 4.9,
    reviewCount: 55,
    type: 'Villa',
    beds: 3,
    baths: 2,
    guests: 6,
    images: [
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    amenities: ['WiFi', 'Private Pool', 'Kitchen', 'Parking', 'Garden', 'Ocean View', 'Beach Access'],
    verified: true,
    instantBook: false,
    hostId: 'h10',
    hostName: 'Emily Kadzo',
    hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    description: 'Luxurious villa on Msambweni\'s pristine beach. Private pool, stunning ocean views, and tranquil setting away from the crowds.',
    wifiSpeed: '45 Mbps',
    electricity: 'Stable (backup generator)',
    water: 'Reliable',
    safetyScore: 9.2,
    tag: 'luxury',
    lat: -4.47,
    lng: 39.47,
  },
  {
    id: '11',
    title: 'Malindi Beachfront Apartment',
    location: 'Malindi, Kilifi County',
    price: 6200,
    rating: 4.72,
    reviewCount: 84,
    type: 'Apartment',
    beds: 2,
    baths: 2,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
    ],
    amenities: ['WiFi', 'Pool', 'Beach Access', 'Kitchen', 'AC', 'Balcony'],
    verified: true,
    instantBook: true,
    hostId: 'h11',
    hostName: 'Hassan Mwakio',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
    description: 'Bright beachfront apartment steps from Malindi\'s famous white beaches. Pool, ocean breeze, and a balcony perfect for sundowners.',
    wifiSpeed: '40 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.8,
    tag: 'trending',
    lat: -3.2175,
    lng: 40.1169,
  },
  {
    id: '12',
    title: 'Tiwi Beach Luxury Villa',
    location: 'Tiwi, Kwale',
    price: 18000,
    rating: 4.95,
    reviewCount: 31,
    type: 'Villa',
    beds: 5,
    baths: 4,
    guests: 10,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: ['WiFi', 'Pool', 'Beach Access', 'Garden', 'Parking', 'Security', 'Kitchen', 'Home Theater'],
    verified: true,
    instantBook: false,
    hostId: 'h12',
    hostName: 'Patricia Kazungu',
    hostAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100',
    description: 'Ultra-luxury beachfront villa in Tiwi with direct beach access. Fully staffed with chef and housekeeper. Perfect for exclusive retreats.',
    wifiSpeed: '100 Mbps',
    electricity: 'Stable (full inverter backup)',
    water: 'Reliable (borehole)',
    safetyScore: 9.5,
    tag: 'luxury',
    lat: -4.25,
    lng: 39.58,
  },
];

export const BOOKINGS = [
  {
    id: 'BK001',
    propertyId: '1',
    propertyTitle: 'Luxury Ocean View Suite',
    propertyImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400',
    location: 'Nyali, Mombasa',
    checkIn: '2026-04-15',
    checkOut: '2026-04-18',
    guests: 2,
    totalAmount: 28500,
    status: 'confirmed',
    hostName: 'Amina Wanjiru',
    hostPhone: '+254 712 345 678',
    accessCode: 'HA-2847',
    checkInInstructions: 'Use the keypad code HA-2847. Lockbox is on the right side of the main door.',
    cancellationPolicy: 'moderate',
  },
  {
    id: 'BK002',
    propertyId: '3',
    propertyTitle: 'Mtwapa Beach Studio',
    propertyImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
    location: 'Mtwapa, Mombasa',
    checkIn: '2026-03-28',
    checkOut: '2026-03-30',
    guests: 1,
    totalAmount: 9500,
    status: 'completed',
    hostName: 'Grace Mwacharo',
    hostPhone: '+254 721 987 654',
    accessCode: 'WS-9123',
    checkInInstructions: 'Code is WS-9123. Building near Mtwapa Creek.',
    cancellationPolicy: 'flexible',
  },
  {
    id: 'BK003',
    propertyId: '2',
    propertyTitle: 'Watamu Beachfront Villa',
    propertyImage: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=400',
    location: 'Watamu, Kilifi County',
    checkIn: '2026-05-01',
    checkOut: '2026-05-04',
    guests: 4,
    totalAmount: 52000,
    status: 'pending',
    hostName: 'David Mwacharo',
    hostPhone: '+254 700 111 222',
    accessCode: null,
    checkInInstructions: 'Host will meet you at the main gate near Watamu Junction.',
    cancellationPolicy: 'strict',
  },
  {
    id: 'BK004',
    propertyId: '7',
    propertyTitle: 'Lamu Stone Town Retreat',
    propertyImage: 'https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=400',
    location: 'Lamu Island, Coast',
    checkIn: '2026-06-10',
    checkOut: '2026-06-14',
    guests: 2,
    totalAmount: 39200,
    status: 'confirmed',
    hostName: 'Fatuma Ali',
    hostPhone: '+254 718 200 100',
    accessCode: 'LM-5541',
    checkInInstructions: 'Take the ferry to Lamu Town. Fatuma will meet you at the jetty.',
    cancellationPolicy: 'moderate',
  },
  {
    id: 'BK005',
    propertyId: '10',
    propertyTitle: 'Msambweni Beach Villa',
    propertyImage: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400',
    location: 'Msambweni, Kwale',
    checkIn: '2026-04-02',
    checkOut: '2026-04-05',
    guests: 4,
    totalAmount: 34500,
    status: 'completed',
    hostName: 'Emily Kadzo',
    hostPhone: '+254 722 334 455',
    accessCode: 'NK-7892',
    checkInInstructions: 'Gate code is NK-7892. Located on Msambweni Beach road.',
    cancellationPolicy: 'flexible',
  },
  {
    id: 'BK006',
    propertyId: '12',
    propertyTitle: 'Tiwi Beach Luxury Villa',
    propertyImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400',
    location: 'Tiwi, Kwale',
    checkIn: '2026-07-20',
    checkOut: '2026-07-23',
    guests: 8,
    totalAmount: 66000,
    status: 'pending',
    hostName: 'Patricia Kazungu',
    hostPhone: '+254 701 555 777',
    accessCode: null,
    checkInInstructions: 'Security will verify your ID at the main gate. Patricia\'s team will show you around.',
    cancellationPolicy: 'strict',
  },
];

export const HOST_STATS = {
  totalRevenue: 347500,
  monthRevenue: 89500,
  weekRevenue: 22000,
  totalBookings: 156,
  monthBookings: 18,
  occupancyRate: 74,
  avgNightlyRate: 8500,
  pendingBookings: 3,
  newMessages: 7,
  totalProperties: 4,
};

export const HOST_PROPERTIES = [
  {
    id: '1',
    title: 'Luxury Ocean View Suite',
    location: 'Nyali, Mombasa',
    type: 'Apartment',
    status: 'active',
    verificationStatus: 'verified',
    bookingsThisMonth: 8,
    avgRating: 4.9,
    earnings: 68000,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400',
  },
  {
    id: '7',
    title: 'Nyali Beach Villa',
    location: 'Nyali, Mombasa',
    type: 'Villa',
    status: 'active',
    verificationStatus: 'verified',
    bookingsThisMonth: 5,
    avgRating: 4.7,
    earnings: 45000,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400',
  },
  {
    id: '8',
    title: 'Coast Studio Apartment',
    location: 'Mombasa CBD',
    type: 'Studio',
    status: 'paused',
    verificationStatus: 'pending',
    bookingsThisMonth: 0,
    avgRating: 0,
    earnings: 0,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
  },
  {
    id: '11',
    title: 'Malindi Beachfront Apartment',
    location: 'Malindi, Kilifi County',
    type: 'Apartment',
    status: 'active',
    verificationStatus: 'verified',
    bookingsThisMonth: 6,
    avgRating: 4.72,
    earnings: 37200,
    image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400',
  },
  {
    id: '12',
    title: 'Tiwi Beach Luxury Villa',
    location: 'Tiwi, Kwale',
    type: 'Villa',
    status: 'active',
    verificationStatus: 'verified',
    bookingsThisMonth: 2,
    avgRating: 4.95,
    earnings: 44000,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400',
  },
];

export const INSPECTIONS = [
  {
    id: 'INS001',
    propertyId: '8',
    propertyTitle: 'Coast Studio Apartment',
    propertyAddress: 'Mombasa CBD, Near Station',
    hostName: 'Amina Wanjiru',
    hostPhone: '+254 712 345 678',
    scheduledDate: '2026-03-25',
    scheduledTime: '10:00 AM',
    status: 'pending',
    priority: 'high',
    inspectorName: null as string | null,
    notes: null as string | null,
    result: null as string | null,
    lat: -4.0532,
    lng: 39.6628,
  },
  {
    id: 'INS002',
    propertyId: '9',
    propertyTitle: 'Kilifi Creek House',
    propertyAddress: 'Kilifi Creek Road, Kilifi',
    hostName: 'Robert Mwangi',
    hostPhone: '+254 733 456 789',
    scheduledDate: '2026-03-26',
    scheduledTime: '2:00 PM',
    status: 'pending',
    priority: 'medium',
    inspectorName: 'James Odhiambo',
    notes: null as string | null,
    result: null as string | null,
    lat: -3.6309,
    lng: 39.8499,
  },
  {
    id: 'INS003',
    propertyId: '3',
    propertyTitle: 'Mtwapa Beach Studio',
    propertyAddress: 'Mtwapa Creek Road, Mombasa',
    hostName: 'Grace Mwacharo',
    hostPhone: '+254 721 987 654',
    scheduledDate: '2026-03-20',
    scheduledTime: '11:00 AM',
    status: 'completed',
    priority: 'low',
    inspectorName: 'Grace Mutua',
    notes: 'Property is in excellent condition. All amenities as listed.',
    result: 'passed',
    lat: -3.95,
    lng: 39.75,
  },
  {
    id: 'INS004',
    propertyId: '11',
    propertyTitle: 'Malindi Beachfront Apartment',
    propertyAddress: 'Malindi Beach Road, Kilifi County',
    hostName: 'Hassan Mwakio',
    hostPhone: '+254 718 200 100',
    scheduledDate: '2026-03-28',
    scheduledTime: '9:00 AM',
    status: 'pending',
    priority: 'high',
    inspectorName: 'Naomi Adhiambo',
    notes: null as string | null,
    result: null as string | null,
    lat: -3.2175,
    lng: 40.1169,
  },
  {
    id: 'INS005',
    propertyId: '7',
    propertyTitle: 'Lamu Stone Town Retreat',
    propertyAddress: 'Lamu Old Town, Lamu Island',
    hostName: 'Fatuma Ali',
    hostPhone: '+254 718 200 100',
    scheduledDate: '2026-03-18',
    scheduledTime: '10:00 AM',
    status: 'completed',
    priority: 'medium',
    inspectorName: 'James Odhiambo',
    notes: 'Stunning property. Rooftop and all rooms match listing photos. Minor: one bathroom tap drips slightly — host notified.',
    result: 'passed',
    lat: -2.2694,
    lng: 40.9022,
  },
  {
    id: 'INS006',
    propertyId: '8',
    propertyTitle: 'Kilifi Creek Cottage',
    propertyAddress: 'Kilifi Creek Road, Kilifi',
    hostName: 'Samuel Charo',
    hostPhone: '+254 733 900 112',
    scheduledDate: '2026-04-01',
    scheduledTime: '1:00 PM',
    status: 'pending',
    priority: 'medium',
    inspectorName: null as string | null,
    notes: null as string | null,
    result: null as string | null,
    lat: -3.63,
    lng: 39.85,
  },
  {
    id: 'INS007',
    propertyId: '12',
    propertyTitle: 'Tiwi Beach Luxury Villa',
    propertyAddress: 'Tiwi Beach, Kwale',
    hostName: 'Patricia Kazungu',
    hostPhone: '+254 701 555 777',
    scheduledDate: '2026-03-15',
    scheduledTime: '3:00 PM',
    status: 'completed',
    priority: 'high',
    inspectorName: 'James Odhiambo',
    notes: 'Stunning beachfront villa. All 5 bedrooms verified, home theater operational, pool in perfect order. Passed all safety checks.',
    result: 'passed',
    lat: -4.25,
    lng: 39.58,
  },
];

export const ADMIN_STATS = {
  totalUsers: 12847,
  totalGuests: 11293,
  totalHosts: 1421,
  totalInspectors: 133,
  totalProperties: 3872,
  activeListings: 3241,
  pendingListings: 147,
  totalBookings: 28934,
  monthBookings: 1872,
  totalRevenue: 48293000,
  monthRevenue: 3241000,
  platformHealth: 98.7,
  pendingDisputes: 12,
};

export const USERS = [
  { id: 'u1', name: 'Amina Wanjiru', email: 'amina@example.com', role: 'host', status: 'active', joined: '2024-01-15', bookings: 0, properties: 3 },
  { id: 'u2', name: 'Brian Otieno', email: 'brian@example.com', role: 'guest', status: 'active', joined: '2024-03-22', bookings: 12, properties: 0 },
  { id: 'u3', name: 'Catherine Mwenda', email: 'cat@example.com', role: 'guest', status: 'active', joined: '2024-05-08', bookings: 4, properties: 0 },
  { id: 'u4', name: 'David Mwacharo', email: 'david@example.com', role: 'host', status: 'active', joined: '2024-02-11', bookings: 0, properties: 2 },
  { id: 'u5', name: 'Eva Kamau', email: 'eva@example.com', role: 'inspector', status: 'active', joined: '2024-07-01', bookings: 0, properties: 0 },
  { id: 'u6', name: 'Frank Mutiso', email: 'frank@example.com', role: 'guest', status: 'suspended', joined: '2024-06-20', bookings: 2, properties: 0 },
  { id: 'u7', name: 'Grace Mwacharo', email: 'grace@example.com', role: 'host', status: 'active', joined: '2023-11-30', bookings: 0, properties: 4 },
  { id: 'u8', name: 'Hassan Mwakio', email: 'hassan@example.com', role: 'host', status: 'active', joined: '2024-04-17', bookings: 0, properties: 2 },
  { id: 'u9', name: 'Irene Chebet', email: 'irene@example.com', role: 'guest', status: 'active', joined: '2024-09-03', bookings: 7, properties: 0 },
  { id: 'u10', name: 'James Odhiambo', email: 'james.o@example.com', role: 'inspector', status: 'active', joined: '2024-08-14', bookings: 0, properties: 0 },
  { id: 'u11', name: 'Kelvin Njau', email: 'kelvin@example.com', role: 'guest', status: 'active', joined: '2025-01-09', bookings: 3, properties: 0 },
  { id: 'u12', name: 'Linda Aoko', email: 'linda@example.com', role: 'guest', status: 'suspended', joined: '2024-11-22', bookings: 1, properties: 0 },
  { id: 'u13', name: 'Mwangi Kariuki', email: 'mwangi@example.com', role: 'host', status: 'active', joined: '2023-08-05', bookings: 0, properties: 5 },
  { id: 'u14', name: 'Naomi Adhiambo', email: 'naomi@example.com', role: 'inspector', status: 'active', joined: '2025-02-28', bookings: 0, properties: 0 },
  { id: 'u15', name: 'Oscar Ruto', email: 'oscar@example.com', role: 'guest', status: 'active', joined: '2024-12-01', bookings: 5, properties: 0 },
];

export const MESSAGES = [
  {
    id: 'm1',
    contactName: 'Amina Wanjiru',
    contactAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=100',
    contactRole: 'Host',
    lastMessage: 'Your check-in code is ready! See you on the 15th 😊',
    timestamp: '2 min ago',
    unread: true,
    propertyTitle: 'Luxury Ocean View Suite',
    messages: [
      { id: 1, sender: 'host', text: 'Hi! Thanks for booking my place.', time: '9:00 AM' },
      { id: 2, sender: 'guest', text: 'Hello! Really excited for the stay.', time: '9:05 AM' },
      { id: 3, sender: 'host', text: 'The check-in process is self-service. I\'ll send you all the details 2 days before.', time: '9:06 AM' },
      { id: 4, sender: 'host', text: 'Your check-in code is ready! See you on the 15th 😊', time: '2:30 PM' },
    ],
  },
  {
    id: 'm2',
    contactName: 'David Mwacharo',
    contactAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    contactRole: 'Host',
    lastMessage: 'I\'ll need to confirm your booking first. Can you share...',
    timestamp: '1 hr ago',
    unread: true,
    propertyTitle: 'Watamu Beachfront Villa',
    messages: [
      { id: 1, sender: 'guest', text: 'Hi David, I\'m interested in a 3-night stay in May.', time: '11:00 AM' },
      { id: 2, sender: 'host', text: 'Welcome! We have availability. How many guests?', time: '11:30 AM' },
      { id: 3, sender: 'host', text: 'I\'ll need to confirm your booking first. Can you share your ID for verification?', time: '11:32 AM' },
    ],
  },
  {
    id: 'm3',
    contactName: 'Grace Mwacharo',
    contactAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    contactRole: 'Host',
    lastMessage: 'Thanks for staying! Please leave a review 🙏',
    timestamp: '3 days ago',
    unread: false,
    propertyTitle: 'Mtwapa Beach Studio',
    messages: [
      { id: 1, sender: 'host', text: 'Thanks for staying! Please leave a review 🙏', time: '10:00 AM' },
    ],
  },
  {
    id: 'm4',
    contactName: 'Fatuma Ali',
    contactAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100',
    contactRole: 'Host',
    lastMessage: 'The ferry departs at 8 AM and 2 PM daily from Mokowe.',
    timestamp: '5 hrs ago',
    unread: true,
    propertyTitle: 'Lamu Stone Town Retreat',
    messages: [
      { id: 1, sender: 'guest', text: 'Hi Fatuma! Very excited about our stay. How do we get to the property from the airport?', time: '8:00 AM' },
      { id: 2, sender: 'host', text: 'Welcome! Fly into Lamu Airport (LAU) then take a tuk-tuk to Mokowe jetty.', time: '9:15 AM' },
      { id: 3, sender: 'host', text: 'The ferry departs at 8 AM and 2 PM daily from Mokowe.', time: '9:16 AM' },
    ],
  },
  {
    id: 'm5',
    contactName: 'Emily Kadzo',
    contactAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    contactRole: 'Host',
    lastMessage: 'Hope you had a great stay! The beach was beautiful this week.',
    timestamp: '1 week ago',
    unread: false,
    propertyTitle: 'Msambweni Beach Villa',
    messages: [
      { id: 1, sender: 'guest', text: 'We just checked out — absolutely magical place!', time: '11:00 AM' },
      { id: 2, sender: 'host', text: 'So glad you enjoyed it! Did you try the local seafood?', time: '11:30 AM' },
      { id: 3, sender: 'guest', text: 'The prawns were amazing! Fresh from the ocean.', time: '11:45 AM' },
      { id: 4, sender: 'host', text: 'Hope you had a great stay! The beach was beautiful this week.', time: '12:00 PM' },
    ],
  },
];

export const NOTIFICATIONS = [
  { id: 1, type: 'booking', title: 'Booking Confirmed', message: 'Your booking for Luxury Ocean View Suite is confirmed!', time: '2 min ago', read: false },
  { id: 2, type: 'reminder', title: 'Check-in Tomorrow', message: 'You check in at Mtwapa Beach Studio tomorrow at 2 PM.', time: '1 hr ago', read: false },
  { id: 3, type: 'promo', title: '20% Off Tonight', message: 'Get 20% off same-day bookings in Mombasa!', time: '3 hrs ago', read: true },
  { id: 4, type: 'system', title: 'Profile Verified', message: 'Your phone number has been successfully verified.', time: '1 day ago', read: true },
  { id: 5, type: 'booking', title: 'New Booking Request', message: 'You have a new booking request for Lamu Stone Town Retreat (Jun 10–14).', time: '2 days ago', read: true },
  { id: 6, type: 'reminder', title: 'Review Reminder', message: 'Share your experience at Msambweni Beach Villa — it helps other guests!', time: '3 days ago', read: false },
  { id: 7, type: 'promo', title: 'Weekend Deal', message: 'Exclusive 15% off beach properties this weekend. Use code BEACH15.', time: '4 days ago', read: true },
];

export const REVIEWS = [
  {
    id: 'r1',
    guestName: 'Brian Otieno',
    guestAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    rating: 5,
    date: 'March 2026',
    comment: 'Absolutely stunning property! The ocean views are even better in person. Amina was a fantastic host, very responsive. Definitely coming back!',
    cleanliness: 5,
    location: 5,
    value: 4,
    hostResponse: 'Thank you Brian! You were a wonderful guest. Hope to host you again 😊',
  },
  {
    id: 'r2',
    guestName: 'Catherine Mwenda',
    guestAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    rating: 5,
    date: 'February 2026',
    comment: 'Perfect getaway! The place was spotlessly clean, the beach access is amazing, and the amenities are top-notch.',
    cleanliness: 5,
    location: 5,
    value: 5,
    hostResponse: null,
  },
  {
    id: 'r3',
    guestName: 'Peter Kamau',
    guestAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    rating: 4,
    date: 'January 2026',
    comment: 'Great location and beautiful apartment. WiFi was a bit slow at times but overall a great stay.',
    cleanliness: 4,
    location: 5,
    value: 4,
    hostResponse: 'Thanks for the feedback Peter! We\'ve upgraded the WiFi since then.',
  },
  {
    id: 'r4',
    guestName: 'Irene Chebet',
    guestAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100',
    rating: 5,
    date: 'March 2026',
    comment: 'Lamu was a dream and the stone house made it even more special. Fatuma\'s hospitality is unmatched. The rooftop at sunset is simply unreal.',
    cleanliness: 5,
    location: 5,
    value: 5,
    hostResponse: 'Thank you Irene! You made the house come alive. Come back anytime 🌊',
  },
  {
    id: 'r5',
    guestName: 'Oscar Ruto',
    guestAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    rating: 5,
    date: 'February 2026',
    comment: 'The Msambweni villa is pure paradise. Private beach access, stunning pool, and Emily was the perfect host. The kids loved the ocean!',
    cleanliness: 5,
    location: 5,
    value: 4,
    hostResponse: 'We loved having your family! The kids were adorable splashing in the waves 🌊',
  },
  {
    id: 'r6',
    guestName: 'Kelvin Njau',
    guestAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    rating: 4,
    date: 'February 2026',
    comment: 'Kilifi Creek was magical. Watching the dhows sail by from the cottage porch was unforgettable. Cottage was cozy and well-equipped.',
    cleanliness: 4,
    location: 5,
    value: 5,
    hostResponse: null,
  },
  {
    id: 'r7',
    guestName: 'Naomi Adhiambo',
    guestAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    rating: 5,
    date: 'January 2026',
    comment: 'Tiwi villa was absolute perfection for our corporate offsite. The beachfront location was incredible, rooms were immaculate, and the pool kept everyone happy after work sessions.',
    cleanliness: 5,
    location: 5,
    value: 4,
    hostResponse: 'So glad the retreat was a success! Patricia\'s team works hard to make every stay exceptional.',
  },
];

export const INSPECTOR_STATS = {
  totalInspections: 47,
  completedThisMonth: 8,
  passRate: 89,
  avgInspectionTime: 2.4,
  pendingInspections: 3,
  scheduledThisWeek: 5,
  distanceCoveredKm: 312,
  reportsSubmitted: 44,
};

export const INSPECTION_CHECKLIST = [
  {
    category: 'Exterior & Entry',
    items: [
      { id: 'e1', label: 'Main entrance accessible and clean', status: null },
      { id: 'e2', label: 'Lockbox/Smart lock functioning', status: null },
      { id: 'e3', label: 'Property signage correct', status: null },
      { id: 'e4', label: 'Parking area adequate', status: null },
    ],
  },
  {
    category: 'Living Area',
    items: [
      { id: 'l1', label: 'Furniture matches listing photos', status: null },
      { id: 'l2', label: 'AC/Heating functional', status: null },
      { id: 'l3', label: 'TV and entertainment working', status: null },
      { id: 'l4', label: 'Cleanliness standard met', status: null },
    ],
  },
  {
    category: 'Bedroom(s)',
    items: [
      { id: 'b1', label: 'Bed count matches listing', status: null },
      { id: 'b2', label: 'Linens and pillows provided', status: null },
      { id: 'b3', label: 'Storage space adequate', status: null },
    ],
  },
  {
    category: 'Kitchen',
    items: [
      { id: 'k1', label: 'Appliances functional (stove, fridge)', status: null },
      { id: 'k2', label: 'Cookware and utensils present', status: null },
      { id: 'k3', label: 'Kitchen clean and hygienic', status: null },
    ],
  },
  {
    category: 'Bathroom(s)',
    items: [
      { id: 'bt1', label: 'Hot water available', status: null },
      { id: 'bt2', label: 'Towels provided', status: null },
      { id: 'bt3', label: 'Plumbing in good condition', status: null },
    ],
  },
  {
    category: 'Utilities & Safety',
    items: [
      { id: 'u1', label: 'WiFi connected and speed tested', status: null },
      { id: 'u2', label: 'Electricity stable', status: null },
      { id: 'u3', label: 'Smoke detector present', status: null },
      { id: 'u4', label: 'Fire extinguisher accessible', status: null },
      { id: 'u5', label: 'Emergency exits marked', status: null },
    ],
  },
];

// ─── Additional Properties ───────────────────────────────────────────────────

// These extend PROPERTIES above
export const EXTRA_PROPERTIES = [
  {
    id: '13',
    title: 'Takaungu Cliffside Villa',
    location: 'Takaungu, Kilifi County',
    price: 13500,
    rating: 4.88,
    reviewCount: 29,
    type: 'Villa',
    beds: 3,
    baths: 2,
    guests: 6,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
    ],
    amenities: ['WiFi', 'Cliff View', 'Pool', 'Kitchen', 'AC', 'Sundeck'],
    verified: true,
    instantBook: false,
    hostId: 'h13',
    hostName: 'John Mwamba',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
    description: 'Dramatic cliffside villa perched above the Indian Ocean in the historic village of Takaungu. Breathtaking sunset views and a private infinity pool.',
    wifiSpeed: '30 Mbps',
    electricity: 'Stable (solar + grid)',
    water: 'Reliable',
    safetyScore: 9.1,
    tag: 'luxury',
    lat: -3.72,
    lng: 39.85,
  },
  {
    id: '14',
    title: 'Galu Beach Suite',
    location: 'Galu, Kwale',
    price: 5800,
    rating: 4.78,
    reviewCount: 61,
    type: 'Apartment',
    beds: 2,
    baths: 1,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
    ],
    amenities: ['WiFi', 'Beach Access', 'Kitchen', 'Balcony', 'AC', 'Parking'],
    verified: true,
    instantBook: true,
    hostId: 'h14',
    hostName: 'Zawadi Mwangi',
    hostAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=100',
    description: 'Modern beachside suite in quiet Galu Beach, south of Diani. Perfect white sand, swaying palms, and outstanding seafood nearby.',
    wifiSpeed: '40 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.9,
    tag: 'trending',
    lat: -4.36,
    lng: 39.55,
  },
  {
    id: '15',
    title: 'Mida Creek Treehouse',
    location: 'Watamu, Kilifi County',
    price: 7800,
    rating: 4.92,
    reviewCount: 45,
    type: 'Cottage',
    beds: 1,
    baths: 1,
    guests: 2,
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800',
      'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800',
    ],
    amenities: ['WiFi', 'Bird Watching', 'Kayak', 'Kitchen', 'Creek View', 'Breakfast'],
    verified: true,
    instantBook: false,
    hostId: 'h15',
    hostName: 'Rose Kahindi',
    hostAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100',
    description: 'Unique eco-treehouse on the edge of Mida Creek biosphere reserve. Wake up to kingfishers and mangrove breezes. Kayak into the creek at sunrise.',
    wifiSpeed: '20 Mbps',
    electricity: 'Solar (reliable)',
    water: 'Rainwater (filtered)',
    safetyScore: 9.3,
    tag: 'luxury',
    lat: -3.36,
    lng: 39.97,
  },
  {
    id: '16',
    title: 'Funzi Island Eco Lodge',
    location: 'Funzi Island, Kwale',
    price: 9500,
    rating: 4.9,
    reviewCount: 22,
    type: 'Villa',
    beds: 2,
    baths: 2,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=800',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
    ],
    amenities: ['Boat Transfer', 'Snorkeling', 'Kitchen', 'Ocean View', 'Breakfast', 'Fishing'],
    verified: true,
    instantBook: false,
    hostId: 'h16',
    hostName: 'Yusef Shee',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    description: 'Secluded island eco-lodge on Funzi Island, accessible only by boat. Pristine coral reefs, mangroves, and absolute tranquility. Boat transfer included.',
    wifiSpeed: '10 Mbps (satellite)',
    electricity: 'Solar (reliable)',
    water: 'Borehole',
    safetyScore: 9.4,
    tag: 'luxury',
    lat: -4.68,
    lng: 39.48,
  },
  {
    id: '17',
    title: 'Shimba Hills Forest Cottage',
    location: 'Shimba Hills, Kwale',
    price: 4800,
    rating: 4.7,
    reviewCount: 38,
    type: 'Cottage',
    beds: 2,
    baths: 1,
    guests: 4,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['WiFi', 'Forest View', 'Kitchen', 'Fireplace', 'Parking', 'Nature Walks'],
    verified: true,
    instantBook: true,
    hostId: 'h17',
    hostName: 'Dorothy Nganga',
    hostAvatar: 'https://images.unsplash.com/photo-1546961342-ea5f62d5a27b?w=100',
    description: 'Charming forest cottage within the Shimba Hills National Reserve. Elephants roam nearby, sable antelopes graze at dusk. A unique coastal hinterland experience.',
    wifiSpeed: '25 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.7,
    tag: 'trending',
    lat: -4.22,
    lng: 39.44,
  },
  {
    id: '18',
    title: 'Mombasa Old Town Riad',
    location: 'Old Town, Mombasa',
    price: 6800,
    rating: 4.85,
    reviewCount: 77,
    type: 'Villa',
    beds: 3,
    baths: 2,
    guests: 6,
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    amenities: ['WiFi', 'Rooftop Terrace', 'Kitchen', 'AC', 'Courtyard', 'History Tours'],
    verified: true,
    instantBook: true,
    hostId: 'h18',
    hostName: 'Omar Abdullah',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    description: 'Beautifully restored Swahili riad in the heart of Mombasa Old Town. Steps from Fort Jesus, the Old Port, and the best biryani on the coast.',
    wifiSpeed: '35 Mbps',
    electricity: 'Stable',
    water: 'Reliable',
    safetyScore: 8.8,
    tag: 'trending',
    lat: -4.063,
    lng: 39.668,
  },
];

// ─── More Bookings ────────────────────────────────────────────────────────────

export const MORE_BOOKINGS = [
  {
    id: 'BK007',
    propertyId: '13',
    propertyTitle: 'Takaungu Cliffside Villa',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
    location: 'Takaungu, Kilifi County',
    checkIn: '2026-04-28',
    checkOut: '2026-05-02',
    guests: 4,
    totalAmount: 54000,
    status: 'confirmed',
    hostName: 'John Mwamba',
    hostPhone: '+254 711 223 344',
    accessCode: 'TK-4412',
    checkInInstructions: 'Turn left at Takaungu junction, villa is 500m down the cliffside path.',
    cancellationPolicy: 'moderate',
  },
  {
    id: 'BK008',
    propertyId: '15',
    propertyTitle: 'Mida Creek Treehouse',
    propertyImage: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=400',
    location: 'Watamu, Kilifi County',
    checkIn: '2026-05-15',
    checkOut: '2026-05-17',
    guests: 2,
    totalAmount: 15600,
    status: 'pending',
    hostName: 'Rose Kahindi',
    hostPhone: '+254 799 556 677',
    accessCode: null,
    checkInInstructions: 'Rose will pick you up at Watamu junction at agreed time.',
    cancellationPolicy: 'strict',
  },
  {
    id: 'BK009',
    propertyId: '18',
    propertyTitle: 'Mombasa Old Town Riad',
    propertyImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400',
    location: 'Old Town, Mombasa',
    checkIn: '2026-03-29',
    checkOut: '2026-03-31',
    guests: 3,
    totalAmount: 13600,
    status: 'completed',
    hostName: 'Omar Abdullah',
    hostPhone: '+254 722 887 009',
    accessCode: 'OT-7711',
    checkInInstructions: 'Enter through the blue door on Ndia Kuu street. Code is OT-7711.',
    cancellationPolicy: 'flexible',
  },
];

// ─── More Users ───────────────────────────────────────────────────────────────

export const MORE_USERS = [
  { id: 'u16', name: 'Patricia Kazungu', email: 'patricia@example.com', role: 'host', status: 'active', joined: '2023-06-15', bookings: 0, properties: 3 },
  { id: 'u17', name: 'Samuel Charo', email: 'samuel@example.com', role: 'host', status: 'active', joined: '2024-01-20', bookings: 0, properties: 2 },
  { id: 'u18', name: 'Zawadi Mwangi', email: 'zawadi@example.com', role: 'host', status: 'active', joined: '2024-08-03', bookings: 0, properties: 1 },
  { id: 'u19', name: 'Achieng Wanjiku', email: 'achieng@example.com', role: 'guest', status: 'active', joined: '2025-01-14', bookings: 6, properties: 0 },
  { id: 'u20', name: 'Baraka Mwakio', email: 'baraka@example.com', role: 'guest', status: 'active', joined: '2025-03-01', bookings: 2, properties: 0 },
  { id: 'u21', name: 'Celine Atieno', email: 'celine@example.com', role: 'inspector', status: 'active', joined: '2024-10-09', bookings: 0, properties: 0 },
  { id: 'u22', name: 'Dennis Mutuku', email: 'dennis@example.com', role: 'inspector', status: 'active', joined: '2025-02-07', bookings: 0, properties: 0 },
  { id: 'u23', name: 'Farida Osman', email: 'farida@example.com', role: 'guest', status: 'active', joined: '2025-03-10', bookings: 1, properties: 0 },
  { id: 'u24', name: 'George Nyambu', email: 'george@example.com', role: 'host', status: 'suspended', joined: '2024-04-22', bookings: 0, properties: 1 },
  { id: 'u25', name: 'Halima Sheikh', email: 'halima@example.com', role: 'guest', status: 'active', joined: '2025-01-30', bookings: 4, properties: 0 },
];
